version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./.db/mysql/${APP_ENV}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
