'use client';

import type { Metadata } from 'next';
import ToastProvider from '../../providers/toast.provider';
import '@/styles/globals.css';
import Header from '../../components/modules/Header/Header';
import Footer from '../../components/modules/Footer/Footer';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import useRedirectByUserCheck from '../../hooks/useRedirectByUserCheck';

// export const metadata: Metadata = {
//   title: 'Ecommerce api full',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // FIXME: Do I need  it on each page in (general) routes?
  const { shouldLoadContent } = useRedirectByUserCheck();
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {shouldLoadContent && (
          <>
            <ProgressBar
              height="4px"
              color="#fffd00"
              options={{ showSpinner: true }}
              shallowRouting
            />
            <ToastProvider>
              <Header />
              <main>{children}</main>
              <Footer />
            </ToastProvider>
          </>
        )}
      </body>
    </html>
  );
}
