import type { Metadata } from 'next'
import { EffectorNext } from '@effector/next'
import ToastProvider from '../providers/toast.provider'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Ecommerce api full',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ToastProvider>
          <EffectorNext>{children}</EffectorNext>
        </ToastProvider>
      </body>
    </html>
  )
}
